export const Country = [
  { id: 1, country: "Argentina" },
  { id: 2, country: "Chile" }
]

export const Provinces = [
  {
    id: 1, id_countrie: 1,
    province: "Buenos Aires",
  },
  {
    id: 2,
    id_countrie: 1,
    province: "Catamarca",
  },
  {
    id: 3,
    id_countrie: 1,
    province: "Chaco",
  },
  {
    id: 4,
    id_countrie: 1,
    province: "Chubut",
  },
  {
    id: 5,
    id_countrie: 1,
    province: "Ciudad Autónoma de Buenos Aires (CABA)",
  },
  {
    id: 6,
    id_countrie: 1,
    province: "Córdoba",
  },
  {
    id: 7,
    id_countrie: 1,
    province: "Corrientes",
  },
  {
    id: 8,
    id_countrie: 1,
    province: "Entre Ríos",
  },
  {
    id: 9,
    id_countrie: 1,
    province: "Formosa",
  },
  {
    id: 10,
    id_countrie: 1,
    province: "Jujuy",
  },
  {
    id: 11,
    id_countrie: 1,
    province: "La Pampa",
  },
  {
    id: 12,
    id_countrie: 1,
    province: "La Rioja",
  },
  {
    id: 13,
    id_countrie: 1,
    province: "Mendoza",
  },
  {
    id: 14,
    id_countrie: 1,
    province: "Misiones",
  },
  {
    id: 15,
    id_countrie: 1,
    province: "Neuquén",
  },
  {
    id: 16,
    id_countrie: 1,
    province: "Río Negro",
  },
  {
    id: 17,
    id_countrie: 1,
    province: "Salta",
  },
  {
    id: 18,
    id_countrie: 1,
    province: "San Juan",
  },
  {
    id: 19,
    id_countrie: 1,
    province: "San Luis",
  },
  {
    id: 20,
    id_countrie: 1,
    province: "Santa Cruz",
  },
  {
    id: 21,
    id_countrie: 1,
    province: "Santa Fe",
  },
  {
    id: 22,
    id_countrie: 1,
    province: "Santiago del Estero",
  },
  {
    id: 23,
    id_countrie: 1,
    province: "Tierra del Fuego, Antártida e Islas del Atlántico Sur",
  },
  {
    id: 24,
    id_countrie: 1,
    province: "Tucumán",
  },
]

export const Cities = [
  {
    id: 1,
    id_province: 6,
    city: 'Córdoba Capital'
  }
]

export const Neighborhood = [
  { id: 1, id_city: 1, neighborhood: '1º DE MAYO' },
  { id: 2, id_city: 1, neighborhood: '1RA. JUNTA' },
  { id: 3, id_city: 1, neighborhood: '20 DE JUNIO' },
  { id: 4, id_city: 1, neighborhood: '23 DE ABRIL' },
  { id: 5, id_city: 1, neighborhood: '25 DE MAYO' },
  { id: 6, id_city: 1, neighborhood: '4 DE FEBRERO' },
  { id: 7, id_city: 1, neighborhood: 'ACHAVAL PEÑA' },
  { id: 8, id_city: 1, neighborhood: 'ACOSTA' },
  { id: 9, id_city: 1, neighborhood: 'AERONAUTICO' },
  { id: 10, id_city: 1, neighborhood: 'AEROPUERTO' },
  { id: 11, id_city: 1, neighborhood: 'ALBERDI' },
  { id: 12, id_city: 1, neighborhood: 'ALBORADA (N)' },
  { id: 13, id_city: 1, neighborhood: 'ALBORADA (S)' },
  { id: 14, id_city: 1, neighborhood: 'ALEJANDRO CENTENO' },
  { id: 15, id_city: 1, neighborhood: 'ALMIRANTE BROWN' },
  { id: 16, id_city: 1, neighborhood: 'ALTA CORDOBA' },
  { id: 17, id_city: 1, neighborhood: 'ALTAMIRA' },
  { id: 18, id_city: 1, neighborhood: 'ALTO ALBERDI' },
  { id: 19, id_city: 1, neighborhood: 'ALTO HERMOSO' },
  { id: 20, id_city: 1, neighborhood: 'ALTO PALERMO' },
  { id: 21, id_city: 1, neighborhood: 'ALTOS DEL CHATEAU' },
  { id: 22, id_city: 1, neighborhood: 'ALTOS DE SANTA ANA' },
  { id: 23, id_city: 1, neighborhood: 'ALTOS DE VELEZ SARSFIELD' },
  { id: 24, id_city: 1, neighborhood: 'ALTOS DE VILLA CABRERA' },
  { id: 25, id_city: 1, neighborhood: 'ALTOS SAN MARTIN' },
  { id: 26, id_city: 1, neighborhood: 'ALTOS SUD DE SAN VICENTE' },
  { id: 27, id_city: 1, neighborhood: 'ALTO VERDE' },
  { id: 28, id_city: 1, neighborhood: 'AMEGHINO NORTE' },
  { id: 29, id_city: 1, neighborhood: 'AMEGHINO SUD' },
  { id: 30, id_city: 1, neighborhood: 'AMPLIACION 1º DE MAYO' },
  { id: 31, id_city: 1, neighborhood: 'AMPLIACION ALTAMIRA' },
  { id: 32, id_city: 1, neighborhood: 'AMPLIACION BENJAMIN MATIENZO' },
  { id: 33, id_city: 1, neighborhood: 'AMPLIACION EMPALME' },
  { id: 34, id_city: 1, neighborhood: 'AMPLIACION FARINA' },
  { id: 35, id_city: 1, neighborhood: 'AMPLIACION GENERAL ARTIGAS' },
  { id: 36, id_city: 1, neighborhood: 'AMPLIACION JARDIN ESPINOSA' },
  { id: 37, id_city: 1, neighborhood: 'AMPLIACION KENNEDY' },
  { id: 38, id_city: 1, neighborhood: 'AMPLIACION LAS PALMAS' },
  { id: 39, id_city: 1, neighborhood: 'AMPLIACION LOS PLATANOS' },
  { id: 40, id_city: 1, neighborhood: 'AMPLIACION PALMAR' },
  { id: 41, id_city: 1, neighborhood: 'AMPLIACION PANAMERICANO' },
  { id: 42, id_city: 1, neighborhood: 'AMPLIACION POETA LUGONES' },
  { id: 43, id_city: 1, neighborhood: 'AMPLIACION PUEYRREDON' },
  { id: 44, id_city: 1, neighborhood: 'AMPLIACION RESIDENCIAL AMERICA' },
  { id: 45, id_city: 1, neighborhood: 'AMPLIACION ROSEDAL' },
  { id: 46, id_city: 1, neighborhood: 'AMPLIACION SAN FERNANDO' },
  { id: 47, id_city: 1, neighborhood: 'AMPLIACION SAN PABLO' },
  { id: 48, id_city: 1, neighborhood: 'AMPLIACION VELEZ SARSFIELD' },
  { id: 49, id_city: 1, neighborhood: 'ANA MARIA ZUMARAN' },
  { id: 50, id_city: 1, neighborhood: 'ANEXO LAS PALMAS' },
  { id: 51, id_city: 1, neighborhood: 'APEADERO LA TABLADA' },
  { id: 52, id_city: 1, neighborhood: 'ARGUELLO' },
  { id: 53, id_city: 1, neighborhood: 'ARGUELLO NORTE' },
  { id: 54, id_city: 1, neighborhood: 'ARSENALES ANEXO' },
  { id: 55, id_city: 1, neighborhood: 'ARTURO CAPDEVILA' },
  { id: 56, id_city: 1, neighborhood: 'A.T. E.' },
  { id: 57, id_city: 1, neighborhood: 'AUTODROMO' },
  { id: 58, id_city: 1, neighborhood: 'AVENIDA' },
  { id: 59, id_city: 1, neighborhood: 'AYACUCHO' },
  { id: 60, id_city: 1, neighborhood: 'BAJADA DE PIEDRA' },
  { id: 61, id_city: 1, neighborhood: 'BAJADA SAN ROQUE' },
  { id: 62, id_city: 1, neighborhood: 'BAJO GALAN' },
  { id: 63, id_city: 1, neighborhood: 'BAJO GENERAL PAZ' },
  { id: 64, id_city: 1, neighborhood: 'BAJO PALERMO' },
  { id: 65, id_city: 1, neighborhood: 'BELLA VISTA' },
  { id: 66, id_city: 1, neighborhood: 'BELLA VISTA OESTE' },
  { id: 67, id_city: 1, neighborhood: 'BENJAMIN POLICARPIO CABRAL' },
  { id: 68, id_city: 1, neighborhood: 'BETANIA' },
  { id: 69, id_city: 1, neighborhood: 'BIALET MASSE' },
  { id: 70, id_city: 1, neighborhood: 'BOEDO' },
  { id: 71, id_city: 1, neighborhood: 'BRIGADIER SAN MARTIN' },
  { id: 72, id_city: 1, neighborhood: 'CABAÑA DEL PILAR' },
  { id: 73, id_city: 1, neighborhood: 'CABO FARINA' },
  { id: 74, id_city: 1, neighborhood: 'CACERES' },
  { id: 75, id_city: 1, neighborhood: 'CALIFORNIA' },
  { id: 76, id_city: 1, neighborhood: 'CAMINO A 60 CUADRAS' },
  { id: 77, id_city: 1, neighborhood: 'CAMINO A SAN CARLOS' },
  { id: 78, id_city: 1, neighborhood: 'CAMINO A VILLA POSE' },
  { id: 79, id_city: 1, neighborhood: 'CARBO' },
  { id: 80, id_city: 1, neighborhood: 'CAROLA LORENZINI' },
  { id: 81, id_city: 1, neighborhood: 'CARRARA' },
  { id: 82, id_city: 1, neighborhood: 'CARRARA DE HORIZONTE' },
  { id: 83, id_city: 1, neighborhood: 'CASEROS' },
  { id: 84, id_city: 1, neighborhood: 'CENTRO' },
  { id: 85, id_city: 1, neighborhood: 'CENTRO AMERICA' },
  { id: 86, id_city: 1, neighborhood: 'CERRO CHICO' },
  { id: 87, id_city: 1, neighborhood: 'CERRO DE LAS ROSAS' },
  { id: 88, id_city: 1, neighborhood: 'CERRO NORTE' },
  { id: 89, id_city: 1, neighborhood: 'CERVECEROS' },
  { id: 90, id_city: 1, neighborhood: 'CHATEAU CARRERAS' },
  { id: 91, id_city: 1, neighborhood: 'CIUDAD DE JUAN PABLO II' },
  { id: 92, id_city: 1, neighborhood: 'CIUDADELA' },
  { id: 93, id_city: 1, neighborhood: 'CIUDAD UNIVERSITARIA' },
  { id: 94, id_city: 1, neighborhood: 'CLAROS DEL BOSQUE' },
  { id: 95, id_city: 1, neighborhood: 'COFICO' },
  { id: 96, id_city: 1, neighborhood: 'COLINAS DE BELLA VISTA' },
  { id: 97, id_city: 1, neighborhood: 'COLINAS DEL CERRO' },
  { id: 98, id_city: 1, neighborhood: 'COLINAS DE VELEZ SARSFIELD' },
  { id: 99, id_city: 1, neighborhood: 'COLON' },
  { id: 100, id_city: 1, neighborhood: 'COLONIA LOLA' },
  { id: 101, id_city: 1, neighborhood: 'COMANDANTE ESPORA' },
  { id: 102, id_city: 1, neighborhood: 'COMERCIAL' },
  { id: 103, id_city: 1, neighborhood: 'CONGRESO' },
  { id: 104, id_city: 1, neighborhood: 'CONSORCIO 16 DE NOVIEMBRE' },
  { id: 105, id_city: 1, neighborhood: 'CONSORCIO ESPERANZA' },
  { id: 106, id_city: 1, neighborhood: 'COOPERATIVA 16 DE NOVIEMBRE' },
  { id: 107, id_city: 1, neighborhood: 'CORRAL DE PALOS' },
  { id: 108, id_city: 1, neighborhood: 'COUNTRY LOS ALGARROBOS' },
  { id: 109, id_city: 1, neighborhood: 'CO.VI.CO.' },
  { id: 110, id_city: 1, neighborhood: 'CRISOL NORTE' },
  { id: 111, id_city: 1, neighborhood: 'CRISOL SUD' },
  { id: 112, id_city: 1, neighborhood: 'CUPANI' },
  { id: 113, id_city: 1, neighborhood: 'DEAN FUNES' },
  { id: 114, id_city: 1, neighborhood: 'DE LOS CUARTETOS' },
  { id: 115, id_city: 1, neighborhood: 'DE MIS SUEÑOS' },
  { id: 116, id_city: 1, neighborhood: 'DOCTA' },
  { id: 117, id_city: 1, neighborhood: 'DR REMO M. COPELLO' },
  { id: 118, id_city: 1, neighborhood: 'DR RENE FAVALORO' },
  { id: 119, id_city: 1, neighborhood: 'DUCASSE' },
  { id: 120, id_city: 1, neighborhood: 'EJERCITO ARGENTINO' },
  { id: 121, id_city: 1, neighborhood: 'EL BOSQUE' },
  { id: 122, id_city: 1, neighborhood: 'EL CABILDO' },
  { id: 123, id_city: 1, neighborhood: 'EL CERRITO' },
  { id: 124, id_city: 1, neighborhood: 'EL PUEBLITO' },
  { id: 125, id_city: 1, neighborhood: 'EL QUEBRACHAL' },
  { id: 126, id_city: 1, neighborhood: 'EL QUEBRACHO' },
  { id: 127, id_city: 1, neighborhood: 'EL REFUGIO' },
  { id: 128, id_city: 1, neighborhood: 'EL TREBOL' },
  { id: 129, id_city: 1, neighborhood: 'EL TROPEZON' },
  { id: 130, id_city: 1, neighborhood: 'EL VIEJO ALGARROBO' },
  { id: 131, id_city: 1, neighborhood: 'EMAUS' },
  { id: 132, id_city: 1, neighborhood: 'EMPALME' },
  { id: 133, id_city: 1, neighborhood: 'EMPALME CASAS DE OBREROS Y EMPLEADOS' },
  { id: 134, id_city: 1, neighborhood: 'ESCOBAR' },
  { id: 135, id_city: 1, neighborhood: 'ESTACION FERREYRA' },
  { id: 136, id_city: 1, neighborhood: 'ESTACION FLORES' },
  { id: 137, id_city: 1, neighborhood: 'EVITA' },
  { id: 138, id_city: 1, neighborhood: 'FERRER' },
  { id: 139, id_city: 1, neighborhood: 'FERREYRA' },
  { id: 140, id_city: 1, neighborhood: 'FERROVIARIO  MITRE' },
  { id: 141, id_city: 1, neighborhood: 'FINCA LA DOROTEA' },
  { id: 142, id_city: 1, neighborhood: 'FINCAS DEL SUR' },
  { id: 143, id_city: 1, neighborhood: 'GENERAL ARENALES' },
  { id: 144, id_city: 1, neighborhood: 'GENERAL ARTIGAS' },
  { id: 145, id_city: 1, neighborhood: 'GENERAL BELGRANO' },
  { id: 146, id_city: 1, neighborhood: 'GENERAL BUSTOS' },
  { id: 147, id_city: 1, neighborhood: 'GENERAL MOSCONI' },
  { id: 148, id_city: 1, neighborhood: 'GENERAL PAZ' },
  { id: 149, id_city: 1, neighborhood: 'GENERAL PUEYRREDON' },
  { id: 150, id_city: 1, neighborhood: 'GENERAL SAVIO' },
  { id: 151, id_city: 1, neighborhood: 'GRANADERO PRINGLES' },
  { id: 152, id_city: 1, neighborhood: 'GRANJA DE FUNES' },
  { id: 153, id_city: 1, neighborhood: 'GUARNICION AREA CBA' },
  { id: 154, id_city: 1, neighborhood: 'GUARNICION MILITAR CBA' },
  { id: 155, id_city: 1, neighborhood: 'GUAYAQUIL' },
  { id: 156, id_city: 1, neighborhood: 'GUEMES' },
  { id: 157, id_city: 1, neighborhood: 'GUIÑAZU' },
  { id: 158, id_city: 1, neighborhood: 'GUIÑAZU SUD' },
  { id: 159, id_city: 1, neighborhood: 'HIPOLITO IRIGOYEN' },
  { id: 160, id_city: 1, neighborhood: 'HOGAR PROPIO' },
  { id: 161, id_city: 1, neighborhood: 'HORIZONTE' },
  { id: 162, id_city: 1, neighborhood: 'INAUDI' },
  { id: 163, id_city: 1, neighborhood: 'INDEPENDENCIA' },
  { id: 164, id_city: 1, neighborhood: 'INDUSTRIAL ESTE' },
  { id: 165, id_city: 1, neighborhood: 'INDUSTRIAL OESTE' },
  { id: 166, id_city: 1, neighborhood: 'IPONA' },
  { id: 167, id_city: 1, neighborhood: 'IRUPE' },
  { id: 168, id_city: 1, neighborhood: 'ITUZAINGO' },
  { id: 169, id_city: 1, neighborhood: 'ITUZAINGO ANEXO' },
  { id: 170, id_city: 1, neighborhood: 'ITUZAINGO II' },
  { id: 171, id_city: 1, neighborhood: 'JARDIN' },
  { id: 172, id_city: 1, neighborhood: 'JARDIN DEL PILAR' },
  { id: 173, id_city: 1, neighborhood: 'JARDIN DEL SUD' },
  { id: 174, id_city: 1, neighborhood: 'JARDIN ESPINOSA' },
  { id: 175, id_city: 1, neighborhood: 'JARDIN HIPODROMO' },
  { id: 176, id_city: 1, neighborhood: 'JERONIMO LUIS DE CABRERA' },
  { id: 177, id_city: 1, neighborhood: 'JOCKEY' },
  { id: 178, id_city: 1, neighborhood: 'JOCKEY CLUB' },
  { id: 179, id_city: 1, neighborhood: 'JOSE HERNANDEZ' },
  { id: 180, id_city: 1, neighborhood: 'JOSE IGNACIO DIAZ 1A SECCION' },
  { id: 181, id_city: 1, neighborhood: 'JOSE IGNACIO DIAZ 2A SECCION' },
  { id: 182, id_city: 1, neighborhood: 'JOSE IGNACIO DIAZ 3A SECCION' },
  { id: 183, id_city: 1, neighborhood: 'JOSE IGNACIO RUCCI' },
  { id: 184, id_city: 1, neighborhood: 'JUAN B. JUSTO' },
  { id: 185, id_city: 1, neighborhood: 'JUAN XXIII' },
  { id: 186, id_city: 1, neighborhood: 'JUNIORS' },
  { id: 187, id_city: 1, neighborhood: 'KAIROS' },
  { id: 188, id_city: 1, neighborhood: 'KENNEDY' },
  { id: 189, id_city: 1, neighborhood: 'LA CARBONADA' },
  { id: 190, id_city: 1, neighborhood: 'LA CAROLINA' },
  { id: 191, id_city: 1, neighborhood: 'LA ESPERANZA' },
  { id: 192, id_city: 1, neighborhood: 'LA FLORESTA' },
  { id: 193, id_city: 1, neighborhood: 'LA FRANCE' },
  { id: 194, id_city: 1, neighborhood: 'LA FRATERNIDAD' },
  { id: 195, id_city: 1, neighborhood: 'LA HORTENSIA' },
  { id: 196, id_city: 1, neighborhood: 'LAMADRID' },
  { id: 197, id_city: 1, neighborhood: 'LA RESERVA' },
  { id: 198, id_city: 1, neighborhood: 'LA SALLE' },
  { id: 199, id_city: 1, neighborhood: 'LAS CAÑITAS' },
  { id: 200, id_city: 1, neighborhood: 'LAS CAÑUELAS' },
  { id: 201, id_city: 1, neighborhood: 'LAS DALIAS' },
  { id: 202, id_city: 1, neighborhood: 'LAS DELICIAS' },
  { id: 203, id_city: 1, neighborhood: 'LAS FLORES' },
  { id: 204, id_city: 1, neighborhood: 'LAS HUERTILLAS' },
  { id: 205, id_city: 1, neighborhood: 'LAS LILAS' },
  { id: 206, id_city: 1, neighborhood: 'LAS MAGNOLIAS' },
  { id: 207, id_city: 1, neighborhood: 'LAS MARGARITAS' },
  { id: 208, id_city: 1, neighborhood: 'LAS PALMAS' },
  { id: 209, id_city: 1, neighborhood: 'LAS PLAYAS' },
  { id: 210, id_city: 1, neighborhood: 'LAS ROSAS' },
  { id: 211, id_city: 1, neighborhood: 'LAS VIOLETAS' },
  { id: 212, id_city: 1, neighborhood: 'LA TOMA' },
  { id: 213, id_city: 1, neighborhood: 'LICEO GENERAL PAZ' },
  { id: 214, id_city: 1, neighborhood: 'LOMAS DE LA CAROLINA' },
  { id: 215, id_city: 1, neighborhood: 'LOMAS DE SAN MARTIN' },
  { id: 216, id_city: 1, neighborhood: 'LOS ALAMOS' },
  { id: 217, id_city: 1, neighborhood: 'LOS ANGELES' },
  { id: 218, id_city: 1, neighborhood: 'LOS BOULEVARES' },
  { id: 219, id_city: 1, neighborhood: 'LOS CEIBOS' },
  { id: 220, id_city: 1, neighborhood: 'LOS CHINGOLOS' },
  { id: 221, id_city: 1, neighborhood: 'LOS EUCALIPTUS' },
  { id: 222, id_city: 1, neighborhood: 'LOS FILTROS' },
  { id: 223, id_city: 1, neighborhood: 'LOS FRESNOS' },
  { id: 224, id_city: 1, neighborhood: 'LOS GIGANTES' },
  { id: 225, id_city: 1, neighborhood: 'LOS GRANADOS' },
  { id: 226, id_city: 1, neighborhood: 'LOS HORNILLOS' },
  { id: 227, id_city: 1, neighborhood: 'LOS JACARANDAES' },
  { id: 228, id_city: 1, neighborhood: 'LOS JOSEFINOS' },
  { id: 229, id_city: 1, neighborhood: 'LOS NARANJOS' },
  { id: 230, id_city: 1, neighborhood: 'LOS OLMOS' },
  { id: 231, id_city: 1, neighborhood: 'LOS OLMOS SUD' },
  { id: 232, id_city: 1, neighborhood: 'LOS PARAISOS' },
  { id: 233, id_city: 1, neighborhood: 'LOS PINOS' },
  { id: 234, id_city: 1, neighborhood: 'LOS PLATANOS' },
  { id: 235, id_city: 1, neighborhood: 'LOS ROBLES' },
  { id: 236, id_city: 1, neighborhood: 'LOS SAUCES' },
  { id: 237, id_city: 1, neighborhood: 'LOURDES' },
  { id: 238, id_city: 1, neighborhood: 'MAIPU 1A SECCION' },
  { id: 239, id_city: 1, neighborhood: 'MAIPU 2A SECCION' },
  { id: 240, id_city: 1, neighborhood: 'MALDONADO' },
  { id: 241, id_city: 1, neighborhood: 'MANANTIALES' },
  { id: 242, id_city: 1, neighborhood: 'MANANTIALES II' },
  { id: 243, id_city: 1, neighborhood: 'MARCELO T. DE ALVEAR' },
  { id: 244, id_city: 1, neighborhood: 'MARCOS SASTRE' },
  { id: 245, id_city: 1, neighborhood: 'MARECHAL' },
  { id: 246, id_city: 1, neighborhood: 'MARIA LASTENIA' },
  { id: 247, id_city: 1, neighborhood: 'MARIANO BALCARCE' },
  { id: 248, id_city: 1, neighborhood: 'MARIANO FRAGUEIRO' },
  { id: 249, id_city: 1, neighborhood: 'MARQUES DE SOBREMONTE' },
  { id: 250, id_city: 1, neighborhood: 'MAURIZI' },
  { id: 251, id_city: 1, neighborhood: 'MERCANTIL' },
  { id: 252, id_city: 1, neighborhood: 'MILITAR GENERAL DEHEZA' },
  { id: 253, id_city: 1, neighborhood: 'MIRADOR' },
  { id: 254, id_city: 1, neighborhood: 'MIRADOR DEL CHATEAU' },
  { id: 255, id_city: 1, neighborhood: 'MIRALTA' },
  { id: 256, id_city: 1, neighborhood: 'MIRIZI' },
  { id: 257, id_city: 1, neighborhood: 'MULLER' },
  { id: 258, id_city: 1, neighborhood: 'MUTUAL DE LOS DOCENTES' },
  { id: 259, id_city: 1, neighborhood: 'NICOLAS AVELLANEDA' },
  { id: 260, id_city: 1, neighborhood: 'NUESTRO HOGAR II' },
  { id: 261, id_city: 1, neighborhood: 'NUESTRO HOGAR III' },
  { id: 262, id_city: 1, neighborhood: 'NUEVA CORDOBA' },
  { id: 263, id_city: 1, neighborhood: 'NUEVA CORDOBA ANEXA' },
  { id: 264, id_city: 1, neighborhood: 'NUEVA ITALIA' },
  { id: 265, id_city: 1, neighborhood: 'NUEVO URCA' },
  { id: 266, id_city: 1, neighborhood: 'OBISPO ANGELELLI' },
  { id: 267, id_city: 1, neighborhood: 'OBRERO' },
  { id: 268, id_city: 1, neighborhood: 'OBSERVATORIO' },
  { id: 269, id_city: 1, neighborhood: 'OMBU' },
  { id: 270, id_city: 1, neighborhood: 'OÑA' },
  { id: 271, id_city: 1, neighborhood: 'O.S.N.' },
  { id: 272, id_city: 1, neighborhood: 'PADRE CLARET' },
  { id: 273, id_city: 1, neighborhood: 'PALMAR' },
  { id: 274, id_city: 1, neighborhood: 'PANAMERICANO' },
  { id: 275, id_city: 1, neighborhood: 'PARQUE ALAMEDA' },
  { id: 276, id_city: 1, neighborhood: 'PARQUE ATLANTICA' },
  { id: 277, id_city: 1, neighborhood: 'PARQUE CAPITAL' },
  { id: 278, id_city: 1, neighborhood: 'PARQUE CAPITAL SUR' },
  { id: 279, id_city: 1, neighborhood: 'PARQUE CHACABUCO' },
  { id: 280, id_city: 1, neighborhood: 'PARQUE CHATEAU CARRERAS' },
  { id: 281, id_city: 1, neighborhood: 'PARQUE COREMA' },
  { id: 282, id_city: 1, neighborhood: 'PARQUE DEL ESTE' },
  { id: 283, id_city: 1, neighborhood: 'PARQUE DON BOSCO' },
  { id: 284, id_city: 1, neighborhood: 'PARQUE FUTURA' },
  { id: 285, id_city: 1, neighborhood: 'PARQUE JORGE NEWBERY' },
  { id: 286, id_city: 1, neighborhood: 'PARQUE LATINO' },
  { id: 287, id_city: 1, neighborhood: 'PARQUE LICEO 1A SECCION' },
  { id: 288, id_city: 1, neighborhood: 'PARQUE LICEO 2A SECCION' },
  { id: 289, id_city: 1, neighborhood: 'PARQUE LICEO 3A SECCION' },
  { id: 290, id_city: 1, neighborhood: 'PARQUE LOS MOLINOS' },
  { id: 291, id_city: 1, neighborhood: 'PARQUE MODELO' },
  { id: 292, id_city: 1, neighborhood: 'PARQUE MONTECRISTO' },
  { id: 293, id_city: 1, neighborhood: 'PARQUE REPUBLICA' },
  { id: 294, id_city: 1, neighborhood: 'PARQUE SAN CARLOS' },
  { id: 295, id_city: 1, neighborhood: 'PARQUE SAN VICENTE' },
  { id: 296, id_city: 1, neighborhood: 'PARQUE SARMIENTO' },
  { id: 297, id_city: 1, neighborhood: 'PARQUE TABLADA' },
  { id: 298, id_city: 1, neighborhood: 'PARQUE VELEZ SARSFIELD' },
  { id: 299, id_city: 1, neighborhood: 'PASO DE LOS ANDES' },
  { id: 300, id_city: 1, neighborhood: 'PATRIA' },
  { id: 301, id_city: 1, neighborhood: 'PATRICIOS' },
  { id: 302, id_city: 1, neighborhood: 'PATRICIOS ESTE' },
  { id: 303, id_city: 1, neighborhood: 'PATRICIOS NORTE' },
  { id: 304, id_city: 1, neighborhood: 'PATRICIOS OESTE' },
  { id: 305, id_city: 1, neighborhood: 'POETA LUGONES' },
  { id: 306, id_city: 1, neighborhood: 'POLICIAL' },
  { id: 307, id_city: 1, neighborhood: 'PORTAL DE CORDOBA' },
  { id: 308, id_city: 1, neighborhood: 'PORTAL DEL JACARANDA' },
  { id: 309, id_city: 1, neighborhood: 'POSTA DE VARGAS' },
  { id: 310, id_city: 1, neighborhood: 'PROVIDENCIA' },
  { id: 311, id_city: 1, neighborhood: 'PUENTE BLANCO' },
  { id: 312, id_city: 1, neighborhood: 'QUEBRADA DE LAS ROSAS' },
  { id: 313, id_city: 1, neighborhood: 'QUINTA SANTA ANA' },
  { id: 314, id_city: 1, neighborhood: 'QUINTAS DE ARGUELLO' },
  { id: 315, id_city: 1, neighborhood: 'QUINTAS DE FERREYRA' },
  { id: 316, id_city: 1, neighborhood: 'QUINTAS DE FLORES' },
  { id: 317, id_city: 1, neighborhood: 'QUINTAS DE ITALIA' },
  { id: 318, id_city: 1, neighborhood: 'QUINTAS DEL SUR' },
  { id: 319, id_city: 1, neighborhood: 'QUINTAS DE SAN JORGE' },
  { id: 320, id_city: 1, neighborhood: 'RAMON J. CARCANO' },
  { id: 321, id_city: 1, neighborhood: 'RECREO DEL NORTE' },
  { id: 322, id_city: 1, neighborhood: 'REMEDIOS DE ESCALADA' },
  { id: 323, id_city: 1, neighborhood: 'RENACIMIENTO' },
  { id: 324, id_city: 1, neighborhood: 'RENE FAVALORO SUD' },
  { id: 325, id_city: 1, neighborhood: 'RESIDENCIAL AMERICA' },
  { id: 326, id_city: 1, neighborhood: 'RESIDENCIAL ARAGON' },
  { id: 327, id_city: 1, neighborhood: 'RESIDENCIAL OLIVOS' },
  { id: 328, id_city: 1, neighborhood: 'RESIDENCIAL SAN CARLOS' },
  { id: 329, id_city: 1, neighborhood: 'RESIDENCIAL SAN JORGE' },
  { id: 330, id_city: 1, neighborhood: 'RESIDENCIAL SAN ROQUE' },
  { id: 331, id_city: 1, neighborhood: 'RESIDENCIAL SUD' },
  { id: 332, id_city: 1, neighborhood: 'RESIDENCIAL VELEZ SARSFIELD' },
  { id: 333, id_city: 1, neighborhood: 'RIVADAVIA' },
  { id: 334, id_city: 1, neighborhood: 'RIVERA INDARTE' },
  { id: 335, id_city: 1, neighborhood: 'ROCIO DEL SUR' },
  { id: 336, id_city: 1, neighborhood: 'ROGELIO MARTINEZ' },
  { id: 337, id_city: 1, neighborhood: 'ROSEDAL' },
  { id: 338, id_city: 1, neighborhood: 'SACCHI' },
  { id: 339, id_city: 1, neighborhood: 'SAN ANTONIO' },
  { id: 340, id_city: 1, neighborhood: 'SAN CAYETANO' },
  { id: 341, id_city: 1, neighborhood: 'SAN DANIEL' },
  { id: 342, id_city: 1, neighborhood: 'SAN FELIPE' },
  { id: 343, id_city: 1, neighborhood: 'SAN FERNANDO' },
  { id: 344, id_city: 1, neighborhood: 'SAN FRANCISCO' },
  { id: 345, id_city: 1, neighborhood: 'SAN IGNACIO' },
  { id: 346, id_city: 1, neighborhood: 'SAN JAVIER' },
  { id: 347, id_city: 1, neighborhood: 'SAN JOSE' },
  { id: 348, id_city: 1, neighborhood: 'SAN LORENZO NORTE' },
  { id: 349, id_city: 1, neighborhood: 'SAN LORENZO (S)' },
  { id: 350, id_city: 1, neighborhood: 'SAN LUIS DE FRANCIA' },
  { id: 351, id_city: 1, neighborhood: 'SAN MARCELO' },
  { id: 352, id_city: 1, neighborhood: 'SAN MARTIN' },
  { id: 353, id_city: 1, neighborhood: 'SAN MARTIN ANEXO' },
  { id: 354, id_city: 1, neighborhood: 'SAN MARTIN NORTE' },
  { id: 355, id_city: 1, neighborhood: 'SAN NICOLAS' },
  { id: 356, id_city: 1, neighborhood: 'SAN PABLO' },
  { id: 357, id_city: 1, neighborhood: 'SAN PEDRO NOLASCO' },
  { id: 358, id_city: 1, neighborhood: 'SAN RAFAEL' },
  { id: 359, id_city: 1, neighborhood: 'SAN RAMON' },
  { id: 360, id_city: 1, neighborhood: 'SAN SALVADOR' },
  { id: 361, id_city: 1, neighborhood: 'SANTA ANA RESIDENCIAL' },
  { id: 362, id_city: 1, neighborhood: 'SANTA CECILIA' },
  { id: 363, id_city: 1, neighborhood: 'SANTA CLARA DE ASIS' },
  { id: 364, id_city: 1, neighborhood: 'SANTA ISABEL 1A SECCION' },
  { id: 365, id_city: 1, neighborhood: 'SANTA ISABEL 2A SECCION' },
  { id: 366, id_city: 1, neighborhood: 'SANTA ISABEL 3A SECCION' },
  { id: 367, id_city: 1, neighborhood: 'SANTA RITA' },
  { id: 368, id_city: 1, neighborhood: 'SANTA ROSA RESIDENCIAL' },
  { id: 369, id_city: 1, neighborhood: 'SAN VICENTE' },
  { id: 370, id_city: 1, neighborhood: 'SARGENTO CABRAL' },
  { id: 371, id_city: 1, neighborhood: 'SARMIENTO' },
  { id: 372, id_city: 1, neighborhood: 'SD' },
  { id: 373, id_city: 1, neighborhood: 'S.E.P.' },
  { id: 374, id_city: 1, neighborhood: 'SIETE SOLES' },
  { id: 375, id_city: 1, neighborhood: 'SIN NOMBRE' },
  { id: 376, id_city: 1, neighborhood: 'SMATA' },
  { id: 377, id_city: 1, neighborhood: 'SOLARES DE SANTA MARIA' },
  { id: 378, id_city: 1, neighborhood: 'SUAREZ' },
  { id: 379, id_city: 1, neighborhood: 'TABLADA PARK' },
  { id: 380, id_city: 1, neighborhood: 'TALLERES (E)' },
  { id: 381, id_city: 1, neighborhood: 'TALLERES (O)' },
  { id: 382, id_city: 1, neighborhood: 'TALLERES SUD' },
  { id: 383, id_city: 1, neighborhood: 'TEJAS DE LA CANDELARIA' },
  { id: 384, id_city: 1, neighborhood: 'TEJAS DEL SUR' },
  { id: 385, id_city: 1, neighborhood: 'TEODORO FELS' },
  { id: 386, id_city: 1, neighborhood: 'TRANVIARIOS' },
  { id: 387, id_city: 1, neighborhood: 'TTE. BENJAMIN MATIENZO' },
  { id: 388, id_city: 1, neighborhood: 'UNIVERSITARIO DE HORIZONTE' },
  { id: 389, id_city: 1, neighborhood: 'U.O.C.R.A.' },
  { id: 390, id_city: 1, neighborhood: 'URCA' },
  { id: 391, id_city: 1, neighborhood: 'URITORCO' },
  { id: 392, id_city: 1, neighborhood: 'URQUIZA' },
  { id: 393, id_city: 1, neighborhood: 'VALLE CERCANO' },
  { id: 394, id_city: 1, neighborhood: 'VALLE DEL CERRO' },
  { id: 395, id_city: 1, neighborhood: 'VALLE ESCONDIDO' },
  { id: 396, id_city: 1, neighborhood: 'V.I.C.O.R.' },
  { id: 397, id_city: 1, neighborhood: 'VILLA 9 DE JULIO' },
  { id: 398, id_city: 1, neighborhood: 'VILLA ADELA' },
  { id: 399, id_city: 1, neighborhood: 'VILLA ALBERDI' },
  { id: 400, id_city: 1, neighborhood: 'VILLA ALBERTO' },
  { id: 401, id_city: 1, neighborhood: 'VILLA ALBERTO ANEXO' },
  { id: 402, id_city: 1, neighborhood: 'VILLA ALICIA RISLER' },
  { id: 403, id_city: 1, neighborhood: 'VILLA ALLENDE PARQUE' },
  { id: 404, id_city: 1, neighborhood: 'VILLA ARGENTINA' },
  { id: 405, id_city: 1, neighborhood: 'VILLA ASPASIA' },
  { id: 406, id_city: 1, neighborhood: 'VILLA AVALOS' },
  { id: 407, id_city: 1, neighborhood: 'VILLA AZALAIZ' },
  { id: 408, id_city: 1, neighborhood: 'VILLA AZALAIZ OESTE' },
  { id: 409, id_city: 1, neighborhood: 'VILLA BELGRANO' },
  { id: 410, id_city: 1, neighborhood: 'VILLA BUSTOS' },
  { id: 411, id_city: 1, neighborhood: 'VILLA CABRERA' },
  { id: 412, id_city: 1, neighborhood: 'VILLA CENTENARIO' },
  { id: 413, id_city: 1, neighborhood: 'VILLA CLARET' },
  { id: 414, id_city: 1, neighborhood: 'VILLA CLAUDINA' },
  { id: 415, id_city: 1, neighborhood: 'VILLA CORINA' },
  { id: 416, id_city: 1, neighborhood: 'VILLA CORNU' },
  { id: 417, id_city: 1, neighborhood: 'VILLA CORONEL OLMEDO' },
  { id: 418, id_city: 1, neighborhood: 'VILLA DERNA' },
  { id: 419, id_city: 1, neighborhood: 'VILLA EL LIBERTADOR' },
  { id: 420, id_city: 1, neighborhood: 'VILLA ESQUIU' },
  { id: 421, id_city: 1, neighborhood: 'VILLA EUCARISTICA' },
  { id: 422, id_city: 1, neighborhood: 'VILLA GENERAL URQUIZA' },
  { id: 423, id_city: 1, neighborhood: 'VILLA GRAN PARQUE' },
  { id: 424, id_city: 1, neighborhood: 'VILLA MAFEKIN' },
  { id: 425, id_city: 1, neighborhood: 'VILLA MARTA' },
  { id: 426, id_city: 1, neighborhood: 'VILLA MARTINEZ' },
  { id: 427, id_city: 1, neighborhood: 'VILLA PAEZ' },
  { id: 428, id_city: 1, neighborhood: 'VILLA QUISQUIZACATE' },
  { id: 429, id_city: 1, neighborhood: 'VILLA RETIRO' },
  { id: 430, id_city: 1, neighborhood: 'VILLA RETIRO DE HORIZONTE' },
  { id: 431, id_city: 1, neighborhood: 'VILLA REVOL' },
  { id: 432, id_city: 1, neighborhood: 'VILLA REVOL ANEXO' },
  { id: 433, id_city: 1, neighborhood: 'VILLA RIVADAVIA ANEXO "A"' },
  { id: 434, id_city: 1, neighborhood: 'VILLA RIVERA INDARTE' },
  { id: 435, id_city: 1, neighborhood: 'VILLA SALDAN' },
  { id: 436, id_city: 1, neighborhood: 'VILLA SAN CARLOS' },
  { id: 437, id_city: 1, neighborhood: 'VILLA SAN ISIDRO' },
  { id: 438, id_city: 1, neighborhood: 'VILLA SERRANA' },
  { id: 439, id_city: 1, neighborhood: 'VILLA SIBURU' },
  { id: 440, id_city: 1, neighborhood: 'VILLA SILVANO FUNES' },
  { id: 441, id_city: 1, neighborhood: 'VILLA SOLFERINO' },
  { id: 442, id_city: 1, neighborhood: 'VILLA UNION' },
  { id: 443, id_city: 1, neighborhood: 'VILLA WARCALDE' },
  { id: 444, id_city: 1, neighborhood: 'VILLA ZEPPELIN' },
  { id: 445, id_city: 1, neighborhood: 'VIVERO NORTE' },
  { id: 446, id_city: 1, neighborhood: 'YAPEYU' },
  { id: 447, id_city: 1, neighborhood: 'YOFRE H' },
  { id: 448, id_city: 1, neighborhood: 'YOFRE I' },
  { id: 449, id_city: 1, neighborhood: 'YOFRE NORTE' },
  { id: 450, id_city: 1, neighborhood: 'YOFRE SUD' },
  { id: 451, id_city: 1, neighborhood: 'ZEPA' }
]
