export const Country = [
  { id: 1, country: "Argentina" },
  { id: 2, country: "Chile" }
]

export const Provinces = [
  {
    id: 1, id_countrie: 1,
    province: "Buenos Aires",
  },
  {
    id: 2,
    id_countrie: 1,
    province: "Catamarca",
  },
  {
    id: 3,
    id_countrie: 1,
    province: "Chaco",
  },
  {
    id: 4,
    id_countrie: 1,
    province: "Chubut",
  },
  {
    id: 5,
    id_countrie: 1,
    province: "Ciudad Autónoma de Buenos Aires (CABA)",
  },
  {
    id: 6,
    id_countrie: 1,
    province: "Córdoba",
  },
  {
    id: 7,
    id_countrie: 1,
    province: "Corrientes",
  },
  {
    id: 8,
    id_countrie: 1,
    province: "Entre Ríos",
  },
  {
    id: 9,
    id_countrie: 1,
    province: "Formosa",
  },
  {
    id: 10,
    id_countrie: 1,
    province: "Jujuy",
  },
  {
    id: 11,
    id_countrie: 1,
    province: "La Pampa",
  },
  {
    id: 12,
    id_countrie: 1,
    province: "La Rioja",
  },
  {
    id: 13,
    id_countrie: 1,
    province: "Mendoza",
  },
  {
    id: 14,
    id_countrie: 1,
    province: "Misiones",
  },
  {
    id: 15,
    id_countrie: 1,
    province: "Neuquén",
  },
  {
    id: 16,
    id_countrie: 1,
    province: "Río Negro",
  },
  {
    id: 17,
    id_countrie: 1,
    province: "Salta",
  },
  {
    id: 18,
    id_countrie: 1,
    province: "San Juan",
  },
  {
    id: 19,
    id_countrie: 1,
    province: "San Luis",
  },
  {
    id: 20,
    id_countrie: 1,
    province: "Santa Cruz",
  },
  {
    id: 21,
    id_countrie: 1,
    province: "Santa Fe",
  },
  {
    id: 22,
    id_countrie: 1,
    province: "Santiago del Estero",
  },
  {
    id: 23,
    id_countrie: 1,
    province: "Tierra del Fuego, Antártida e Islas del Atlántico Sur",
  },
  {
    id: 24,
    id_countrie: 1,
    province: "Tucumán",
  },
]

export const Cities = [
  {
    id: 1,
    id_province: 6,
    city: 'Córdoba Capital'
  },
  {
    id: 2,
    id_province: 6,
    city: 'Rio Cuarto'
  }
]

export const Neighborhoods = [
  { id: 1, id_city: 1, neighborhood: '1º De Mayo' },
  { id: 2, id_city: 1, neighborhood: '1ra. Junta' },
  { id: 3, id_city: 1, neighborhood: '20 De Junio' },
  { id: 4, id_city: 1, neighborhood: '23 De Abril' },
  { id: 5, id_city: 1, neighborhood: '25 De Mayo' },
  { id: 6, id_city: 1, neighborhood: '4 De Febrero' },
  { id: 7, id_city: 1, neighborhood: 'Achaval Peña' },
  { id: 8, id_city: 1, neighborhood: 'Acosta' },
  { id: 9, id_city: 1, neighborhood: 'Aeronautico' },
  { id: 10, id_city: 1, neighborhood: 'Aeropuerto' },
  { id: 11, id_city: 1, neighborhood: 'Alberdi' },
  { id: 12, id_city: 1, neighborhood: 'Alborada (n)' },
  { id: 13, id_city: 1, neighborhood: 'Alborada (s)' },
  { id: 14, id_city: 1, neighborhood: 'Alejandro Centeno' },
  { id: 15, id_city: 1, neighborhood: 'Almirante Brown' },
  { id: 16, id_city: 1, neighborhood: 'Alta Cordoba' },
  { id: 17, id_city: 1, neighborhood: 'Altamira' },
  { id: 18, id_city: 1, neighborhood: 'Alto Alberdi' },
  { id: 19, id_city: 1, neighborhood: 'Alto Hermoso' },
  { id: 20, id_city: 1, neighborhood: 'Alto Palermo' },
  { id: 21, id_city: 1, neighborhood: 'Altos Del Chateau' },
  { id: 22, id_city: 1, neighborhood: 'Altos De Santa Ana' },
  { id: 23, id_city: 1, neighborhood: 'Altos De Velez Sarsfield' },
  { id: 24, id_city: 1, neighborhood: 'Altos De Villa Cabrera' },
  { id: 25, id_city: 1, neighborhood: 'Altos San Martin' },
  { id: 26, id_city: 1, neighborhood: 'Altos Sud De San Vicente' },
  { id: 27, id_city: 1, neighborhood: 'Alto Verde' },
  { id: 28, id_city: 1, neighborhood: 'Ameghino Norte' },
  { id: 29, id_city: 1, neighborhood: 'Ameghino Sud' },
  { id: 30, id_city: 1, neighborhood: 'Ampliacion 1º De Mayo' },
  { id: 31, id_city: 1, neighborhood: 'Ampliacion Altamira' },
  { id: 32, id_city: 1, neighborhood: 'Ampliacion Benjamin Matienzo' },
  { id: 33, id_city: 1, neighborhood: 'Ampliacion Empalme' },
  { id: 34, id_city: 1, neighborhood: 'Ampliacion Farina' },
  { id: 35, id_city: 1, neighborhood: 'Ampliacion General Artigas' },
  { id: 36, id_city: 1, neighborhood: 'Ampliacion Jardin Espinosa' },
  { id: 37, id_city: 1, neighborhood: 'Ampliacion Kennedy' },
  { id: 38, id_city: 1, neighborhood: 'Ampliacion Las Palmas' },
  { id: 39, id_city: 1, neighborhood: 'Ampliacion Los Platanos' },
  { id: 40, id_city: 1, neighborhood: 'Ampliacion Palmar' },
  { id: 41, id_city: 1, neighborhood: 'Ampliacion Panamericano' },
  { id: 42, id_city: 1, neighborhood: 'Ampliacion Poeta Lugones' },
  { id: 43, id_city: 1, neighborhood: 'Ampliacion Pueyrredon' },
  { id: 44, id_city: 1, neighborhood: 'Ampliacion Residencial America' },
  { id: 45, id_city: 1, neighborhood: 'Ampliacion Rosedal' },
  { id: 46, id_city: 1, neighborhood: 'Ampliacion San Fernando' },
  { id: 47, id_city: 1, neighborhood: 'Ampliacion San Pablo' },
  { id: 48, id_city: 1, neighborhood: 'Ampliacion Velez Sarsfield' },
  { id: 49, id_city: 1, neighborhood: 'Ana Maria Zumaran' },
  { id: 50, id_city: 1, neighborhood: 'Anexo Las Palmas' },
  { id: 51, id_city: 1, neighborhood: 'Apeadero La Tablada' },
  { id: 52, id_city: 1, neighborhood: 'Arguello' },
  { id: 53, id_city: 1, neighborhood: 'Arguello Norte' },
  { id: 54, id_city: 1, neighborhood: 'Arsenales Anexo' },
  { id: 55, id_city: 1, neighborhood: 'Arturo Capdevila' },
  { id: 56, id_city: 1, neighborhood: 'A.t. E.' },
  { id: 57, id_city: 1, neighborhood: 'Autodromo' },
  { id: 58, id_city: 1, neighborhood: 'Avenida' },
  { id: 59, id_city: 1, neighborhood: 'Ayacucho' },
  { id: 60, id_city: 1, neighborhood: 'Bajada De Piedra' },
  { id: 61, id_city: 1, neighborhood: 'Bajada San Roque' },
  { id: 62, id_city: 1, neighborhood: 'Bajo Galan' },
  { id: 63, id_city: 1, neighborhood: 'Bajo General Paz' },
  { id: 64, id_city: 1, neighborhood: 'Bajo Palermo' },
  { id: 65, id_city: 1, neighborhood: 'Bella Vista' },
  { id: 66, id_city: 1, neighborhood: 'Bella Vista Oeste' },
  { id: 67, id_city: 1, neighborhood: 'Benjamin Policarpio Cabral' },
  { id: 68, id_city: 1, neighborhood: 'Betania' },
  { id: 69, id_city: 1, neighborhood: 'Bialet Masse' },
  { id: 70, id_city: 1, neighborhood: 'Boedo' },
  { id: 71, id_city: 1, neighborhood: 'Brigadier San Martin' },
  { id: 72, id_city: 1, neighborhood: 'Cabaña Del Pilar' },
  { id: 73, id_city: 1, neighborhood: 'Cabo Farina' },
  { id: 74, id_city: 1, neighborhood: 'Caceres' },
  { id: 75, id_city: 1, neighborhood: 'California' },
  { id: 76, id_city: 1, neighborhood: 'Camino A 60 Cuadras' },
  { id: 77, id_city: 1, neighborhood: 'Camino A San Carlos' },
  { id: 78, id_city: 1, neighborhood: 'Camino A Villa Pose' },
  { id: 79, id_city: 1, neighborhood: 'Carbo' },
  { id: 80, id_city: 1, neighborhood: 'Carola Lorenzini' },
  { id: 81, id_city: 1, neighborhood: 'Carrara' },
  { id: 82, id_city: 1, neighborhood: 'Carrara De Horizonte' },
  { id: 83, id_city: 1, neighborhood: 'Caseros' },
  { id: 84, id_city: 1, neighborhood: 'Centro' },
  { id: 85, id_city: 1, neighborhood: 'Centro America' },
  { id: 86, id_city: 1, neighborhood: 'Cerro Chico' },
  { id: 87, id_city: 1, neighborhood: 'Cerro De Las Rosas' },
  { id: 88, id_city: 1, neighborhood: 'Cerro Norte' },
  { id: 89, id_city: 1, neighborhood: 'Cerveceros' },
  { id: 90, id_city: 1, neighborhood: 'Chateau Carreras' },
  { id: 91, id_city: 1, neighborhood: 'Ciudad De Juan Pablo II' },
  { id: 92, id_city: 1, neighborhood: 'Ciudadela' },
  { id: 93, id_city: 1, neighborhood: 'Ciudad Universitaria' },
  { id: 94, id_city: 1, neighborhood: 'Claros Del Bosque' },
  { id: 95, id_city: 1, neighborhood: 'Cofico' },
  { id: 96, id_city: 1, neighborhood: 'Colinas De Bella Vista' },
  { id: 97, id_city: 1, neighborhood: 'Colinas Del Cerro' },
  { id: 98, id_city: 1, neighborhood: 'Colinas De Velez Sarsfield' },
  { id: 99, id_city: 1, neighborhood: 'Colon' },
  { id: 100, id_city: 1, neighborhood: 'Colonia Lola' },
  { id: 101, id_city: 1, neighborhood: 'Comandante Espora' },
  { id: 102, id_city: 1, neighborhood: 'Comercial' },
  { id: 103, id_city: 1, neighborhood: 'Congreso' },
  { id: 104, id_city: 1, neighborhood: 'Consorcio 16 De Noviembre' },
  { id: 105, id_city: 1, neighborhood: 'Consorcio Esperanza' },
  { id: 106, id_city: 1, neighborhood: 'Cooperativa 16 De Noviembre' },
  { id: 107, id_city: 1, neighborhood: 'Corral De Palos' },
  { id: 108, id_city: 1, neighborhood: 'Country Los Algarrobos' },
  { id: 109, id_city: 1, neighborhood: 'Co.vi.co.' },
  { id: 110, id_city: 1, neighborhood: 'Crisol Norte' },
  { id: 111, id_city: 1, neighborhood: 'Crisol Sud' },
  { id: 112, id_city: 1, neighborhood: 'Cupani' },
  { id: 113, id_city: 1, neighborhood: 'Dean Funes' },
  { id: 114, id_city: 1, neighborhood: 'De Los Cuartetos' },
  { id: 115, id_city: 1, neighborhood: 'De Mis Sueños' },
  { id: 116, id_city: 1, neighborhood: 'Docta' },
  { id: 117, id_city: 1, neighborhood: 'Dr Remo M. Copello' },
  { id: 118, id_city: 1, neighborhood: 'Dr Rene Favaloro' },
  { id: 119, id_city: 1, neighborhood: 'Ducasse' },
  { id: 120, id_city: 1, neighborhood: 'Ejercito Argentino' },
  { id: 121, id_city: 1, neighborhood: 'El Bosque' },
  { id: 122, id_city: 1, neighborhood: 'El Cabildo' },
  { id: 123, id_city: 1, neighborhood: 'El Cerrito' },
  { id: 124, id_city: 1, neighborhood: 'El Pueblito' },
  { id: 125, id_city: 1, neighborhood: 'El Quebrachal' },
  { id: 126, id_city: 1, neighborhood: 'El Quebracho' },
  { id: 127, id_city: 1, neighborhood: 'El Refugio' },
  { id: 128, id_city: 1, neighborhood: 'El Trebol' },
  { id: 129, id_city: 1, neighborhood: 'El Tropezon' },
  { id: 130, id_city: 1, neighborhood: 'El Viejo Algarrobo' },
  { id: 131, id_city: 1, neighborhood: 'Emaus' },
  { id: 132, id_city: 1, neighborhood: 'Empalme' },
  { id: 133, id_city: 1, neighborhood: 'Empalme Casas De Obreros Y Empleados' },
  { id: 134, id_city: 1, neighborhood: 'Escobar' },
  { id: 135, id_city: 1, neighborhood: 'Estacion Ferreyra' },
  { id: 136, id_city: 1, neighborhood: 'Estacion Flores' },
  { id: 137, id_city: 1, neighborhood: 'Evita' },
  { id: 138, id_city: 1, neighborhood: 'Ferrer' },
  { id: 139, id_city: 1, neighborhood: 'Ferreyra' },
  { id: 140, id_city: 1, neighborhood: 'Ferroviario  Mitre' },
  { id: 141, id_city: 1, neighborhood: 'Finca La Dorotea' },
  { id: 142, id_city: 1, neighborhood: 'Fincas Del Sur' },
  { id: 143, id_city: 1, neighborhood: 'General Arenales' },
  { id: 144, id_city: 1, neighborhood: 'General Artigas' },
  { id: 145, id_city: 1, neighborhood: 'General Belgrano' },
  { id: 146, id_city: 1, neighborhood: 'General Bustos' },
  { id: 147, id_city: 1, neighborhood: 'General Mosconi' },
  { id: 148, id_city: 1, neighborhood: 'General Paz' },
  { id: 149, id_city: 1, neighborhood: 'General Pueyrredon' },
  { id: 150, id_city: 1, neighborhood: 'General Savio' },
  { id: 151, id_city: 1, neighborhood: 'Granadero Pringles' },
  { id: 152, id_city: 1, neighborhood: 'Granja De Funes' },
  { id: 153, id_city: 1, neighborhood: 'Guarnicion Area Cba' },
  { id: 154, id_city: 1, neighborhood: 'Guarnicion Militar Cba' },
  { id: 155, id_city: 1, neighborhood: 'Guayaquil' },
  { id: 156, id_city: 1, neighborhood: 'Guemes' },
  { id: 157, id_city: 1, neighborhood: 'Guiñazu' },
  { id: 158, id_city: 1, neighborhood: 'Guiñazu Sud' },
  { id: 159, id_city: 1, neighborhood: 'Hipolito Irigoyen' },
  { id: 160, id_city: 1, neighborhood: 'Hogar Propio' },
  { id: 161, id_city: 1, neighborhood: 'Horizonte' },
  { id: 162, id_city: 1, neighborhood: 'Inaudi' },
  { id: 163, id_city: 1, neighborhood: 'Independencia' },
  { id: 164, id_city: 1, neighborhood: 'Industrial Este' },
  { id: 165, id_city: 1, neighborhood: 'Industrial Oeste' },
  { id: 166, id_city: 1, neighborhood: 'Ipona' },
  { id: 167, id_city: 1, neighborhood: 'Irupe' },
  { id: 168, id_city: 1, neighborhood: 'Ituzaingo' },
  { id: 169, id_city: 1, neighborhood: 'Ituzaingo Anexo' },
  { id: 170, id_city: 1, neighborhood: 'Ituzaingo II' },
  { id: 171, id_city: 1, neighborhood: 'Jardin' },
  { id: 172, id_city: 1, neighborhood: 'Jardin Del Pilar' },
  { id: 173, id_city: 1, neighborhood: 'Jardin Del Sud' },
  { id: 174, id_city: 1, neighborhood: 'Jardin Espinosa' },
  { id: 175, id_city: 1, neighborhood: 'Jardin Hipodromo' },
  { id: 176, id_city: 1, neighborhood: 'Jeronimo Luis De Cabrera' },
  { id: 177, id_city: 1, neighborhood: 'Jockey' },
  { id: 178, id_city: 1, neighborhood: 'Jockey Club' },
  { id: 179, id_city: 1, neighborhood: 'Jose Hernandez' },
  { id: 180, id_city: 1, neighborhood: 'Jose Ignacio Diaz 1a Seccion' },
  { id: 181, id_city: 1, neighborhood: 'Jose Ignacio Diaz 2a Seccion' },
  { id: 182, id_city: 1, neighborhood: 'Jose Ignacio Diaz 3a Seccion' },
  { id: 183, id_city: 1, neighborhood: 'Jose Ignacio Rucci' },
  { id: 184, id_city: 1, neighborhood: 'Juan B. Justo' },
  { id: 185, id_city: 1, neighborhood: 'Juan XXIII' },
  { id: 186, id_city: 1, neighborhood: 'Juniors' },
  { id: 187, id_city: 1, neighborhood: 'Kairos' },
  { id: 188, id_city: 1, neighborhood: 'Kennedy' },
  { id: 189, id_city: 1, neighborhood: 'La Carbonada' },
  { id: 190, id_city: 1, neighborhood: 'La Carolina' },
  { id: 191, id_city: 1, neighborhood: 'La Esperanza' },
  { id: 192, id_city: 1, neighborhood: 'La Floresta' },
  { id: 193, id_city: 1, neighborhood: 'La France' },
  { id: 194, id_city: 1, neighborhood: 'La Fraternidad' },
  { id: 195, id_city: 1, neighborhood: 'La Hortensia' },
  { id: 196, id_city: 1, neighborhood: 'Lamadrid' },
  { id: 197, id_city: 1, neighborhood: 'La Reserva' },
  { id: 198, id_city: 1, neighborhood: 'La Salle' },
  { id: 199, id_city: 1, neighborhood: 'Las Cañitas' },
  { id: 200, id_city: 1, neighborhood: 'Las Cañuelas' },
  { id: 201, id_city: 1, neighborhood: 'Las Dalias' },
  { id: 202, id_city: 1, neighborhood: 'Las Delicias' },
  { id: 203, id_city: 1, neighborhood: 'Las Flores' },
  { id: 204, id_city: 1, neighborhood: 'Las Huertillas' },
  { id: 205, id_city: 1, neighborhood: 'Las Lilas' },
  { id: 206, id_city: 1, neighborhood: 'Las Magnolias' },
  { id: 207, id_city: 1, neighborhood: 'Las Margaritas' },
  { id: 208, id_city: 1, neighborhood: 'Las Palmas' },
  { id: 209, id_city: 1, neighborhood: 'Las Playas' },
  { id: 210, id_city: 1, neighborhood: 'Las Rosas' },
  { id: 211, id_city: 1, neighborhood: 'Las Violetas' },
  { id: 212, id_city: 1, neighborhood: 'La Toma' },
  { id: 213, id_city: 1, neighborhood: 'Liceo General Paz' },
  { id: 214, id_city: 1, neighborhood: 'Lomas De La Carolina' },
  { id: 215, id_city: 1, neighborhood: 'Lomas De San Martin' },
  { id: 216, id_city: 1, neighborhood: 'Los Alamos' },
  { id: 217, id_city: 1, neighborhood: 'Los Angeles' },
  { id: 218, id_city: 1, neighborhood: 'Los Boulevares' },
  { id: 219, id_city: 1, neighborhood: 'Los Ceibos' },
  { id: 220, id_city: 1, neighborhood: 'Los Chingolos' },
  { id: 221, id_city: 1, neighborhood: 'Los Eucaliptus' },
  { id: 222, id_city: 1, neighborhood: 'Los Filtros' },
  { id: 223, id_city: 1, neighborhood: 'Los Fresnos' },
  { id: 224, id_city: 1, neighborhood: 'Los Gigantes' },
  { id: 225, id_city: 1, neighborhood: 'Los Granados' },
  { id: 226, id_city: 1, neighborhood: 'Los Hornillos' },
  { id: 227, id_city: 1, neighborhood: 'Los Jacarandaes' },
  { id: 228, id_city: 1, neighborhood: 'Los Josefinos' },
  { id: 229, id_city: 1, neighborhood: 'Los Naranjos' },
  { id: 230, id_city: 1, neighborhood: 'Los Olmos' },
  { id: 231, id_city: 1, neighborhood: 'Los Olmos Sud' },
  { id: 232, id_city: 1, neighborhood: 'Los Paraisos' },
  { id: 233, id_city: 1, neighborhood: 'Los Pinos' },
  { id: 234, id_city: 1, neighborhood: 'Los Platanos' },
  { id: 235, id_city: 1, neighborhood: 'Los Robles' },
  { id: 236, id_city: 1, neighborhood: 'Los Sauces' },
  { id: 237, id_city: 1, neighborhood: 'Lourdes' },
  { id: 238, id_city: 1, neighborhood: 'Maipu 1a Seccion' },
  { id: 239, id_city: 1, neighborhood: 'Maipu 2a Seccion' },
  { id: 240, id_city: 1, neighborhood: 'Maldonado' },
  { id: 241, id_city: 1, neighborhood: 'Manantiales' },
  { id: 242, id_city: 1, neighborhood: 'Manantiales II' },
  { id: 243, id_city: 1, neighborhood: 'Marcelo T. De Alvear' },
  { id: 244, id_city: 1, neighborhood: 'Marcos Sastre' },
  { id: 245, id_city: 1, neighborhood: 'Marechal' },
  { id: 246, id_city: 1, neighborhood: 'Maria Lastenia' },
  { id: 247, id_city: 1, neighborhood: 'Mariano Balcarce' },
  { id: 248, id_city: 1, neighborhood: 'Mariano Fragueiro' },
  { id: 249, id_city: 1, neighborhood: 'Marques De Sobremonte' },
  { id: 250, id_city: 1, neighborhood: 'Maurizi' },
  { id: 251, id_city: 1, neighborhood: 'Mercantil' },
  { id: 252, id_city: 1, neighborhood: 'Militar General Deheza' },
  { id: 253, id_city: 1, neighborhood: 'Mirador' },
  { id: 254, id_city: 1, neighborhood: 'Mirador Del Chateau' },
  { id: 255, id_city: 1, neighborhood: 'Miralta' },
  { id: 256, id_city: 1, neighborhood: 'Mirizi' },
  { id: 257, id_city: 1, neighborhood: 'Muller' },
  { id: 258, id_city: 1, neighborhood: 'Mutual De Los Docentes' },
  { id: 259, id_city: 1, neighborhood: 'Nicolas Avellaneda' },
  { id: 260, id_city: 1, neighborhood: 'Nuestro Hogar II' },
  { id: 261, id_city: 1, neighborhood: 'Nuestro Hogar III' },
  { id: 262, id_city: 1, neighborhood: 'Nueva Cordoba' },
  { id: 263, id_city: 1, neighborhood: 'Nueva Cordoba Anexa' },
  { id: 264, id_city: 1, neighborhood: 'Nueva Italia' },
  { id: 265, id_city: 1, neighborhood: 'Nuevo Urca' },
  { id: 266, id_city: 1, neighborhood: 'Obispo Angelelli' },
  { id: 267, id_city: 1, neighborhood: 'Obrero' },
  { id: 268, id_city: 1, neighborhood: 'Observatorio' },
  { id: 269, id_city: 1, neighborhood: 'Ombu' },
  { id: 270, id_city: 1, neighborhood: 'Oña' },
  { id: 271, id_city: 1, neighborhood: 'O.S.N.' },
  { id: 272, id_city: 1, neighborhood: 'Padre Claret' },
  { id: 273, id_city: 1, neighborhood: 'Palmar' },
  { id: 274, id_city: 1, neighborhood: 'Panamericano' },
  { id: 275, id_city: 1, neighborhood: 'Parque Alameda' },
  { id: 276, id_city: 1, neighborhood: 'Parque Atlantica' },
  { id: 277, id_city: 1, neighborhood: 'Parque Capital' },
  { id: 278, id_city: 1, neighborhood: 'Parque Capital Sur' },
  { id: 279, id_city: 1, neighborhood: 'Parque Chacabuco' },
  { id: 280, id_city: 1, neighborhood: 'Parque Chateau Carreras' },
  { id: 281, id_city: 1, neighborhood: 'Parque Corema' },
  { id: 282, id_city: 1, neighborhood: 'Parque Del Este' },
  { id: 283, id_city: 1, neighborhood: 'Parque Don Bosco' },
  { id: 284, id_city: 1, neighborhood: 'Parque Futura' },
  { id: 285, id_city: 1, neighborhood: 'Parque Jorge Newbery' },
  { id: 286, id_city: 1, neighborhood: 'Parque Latino' },
  { id: 287, id_city: 1, neighborhood: 'Parque Liceo 1a Seccion' },
  { id: 288, id_city: 1, neighborhood: 'Parque Liceo 2a Seccion' },
  { id: 289, id_city: 1, neighborhood: 'Parque Liceo 3a Seccion' },
  { id: 290, id_city: 1, neighborhood: 'Parque Los Molinos' },
  { id: 291, id_city: 1, neighborhood: 'Parque Modelo' },
  { id: 292, id_city: 1, neighborhood: 'Parque Montecristo' },
  { id: 293, id_city: 1, neighborhood: 'Parque Republica' },
  { id: 294, id_city: 1, neighborhood: 'Parque San Carlos' },
  { id: 295, id_city: 1, neighborhood: 'Parque San Vicente' },
  { id: 296, id_city: 1, neighborhood: 'Parque Sarmiento' },
  { id: 297, id_city: 1, neighborhood: 'Parque Tablada' },
  { id: 298, id_city: 1, neighborhood: 'Parque Velez Sarsfield' },
  { id: 299, id_city: 1, neighborhood: 'Paso De Los Andes' },
  { id: 300, id_city: 1, neighborhood: 'Patria' },
  { id: 301, id_city: 1, neighborhood: 'Patricios' },
  { id: 302, id_city: 1, neighborhood: 'Patricios Este' },
  { id: 303, id_city: 1, neighborhood: 'Patricios Norte' },
  { id: 304, id_city: 1, neighborhood: 'Patricios Oeste' },
  { id: 305, id_city: 1, neighborhood: 'Poeta Lugones' },
  { id: 306, id_city: 1, neighborhood: 'Policial' },
  { id: 307, id_city: 1, neighborhood: 'Portal De Cordoba' },
  { id: 308, id_city: 1, neighborhood: 'Portal Del Jacaranda' },
  { id: 309, id_city: 1, neighborhood: 'Posta De Vargas' },
  { id: 310, id_city: 1, neighborhood: 'Providencia' },
  { id: 311, id_city: 1, neighborhood: 'Puente Blanco' },
  { id: 312, id_city: 1, neighborhood: 'Quebrada De Las Rosas' },
  { id: 313, id_city: 1, neighborhood: 'Quinta Santa Ana' },
  { id: 314, id_city: 1, neighborhood: 'Quintas De Arguello' },
  { id: 315, id_city: 1, neighborhood: 'Quintas De Ferreyra' },
  { id: 316, id_city: 1, neighborhood: 'Quintas De Flores' },
  { id: 317, id_city: 1, neighborhood: 'Quintas De Italia' },
  { id: 318, id_city: 1, neighborhood: 'Quintas Del Sur' },
  { id: 319, id_city: 1, neighborhood: 'Quintas De San Jorge' },
  { id: 320, id_city: 1, neighborhood: 'Ramon J. Carcano' },
  { id: 321, id_city: 1, neighborhood: 'Recreo Del Norte' },
  { id: 322, id_city: 1, neighborhood: 'Remedios De Escalada' },
  { id: 323, id_city: 1, neighborhood: 'Renacimiento' },
  { id: 324, id_city: 1, neighborhood: 'Rene Favaloro Sud' },
  { id: 325, id_city: 1, neighborhood: 'Residencial America' },
  { id: 326, id_city: 1, neighborhood: 'Residencial Aragon' },
  { id: 327, id_city: 1, neighborhood: 'Residencial Olivos' },
  { id: 328, id_city: 1, neighborhood: 'Residencial San Carlos' },
  { id: 329, id_city: 1, neighborhood: 'Residencial San Jorge' },
  { id: 330, id_city: 1, neighborhood: 'Residencial San Roque' },
  { id: 331, id_city: 1, neighborhood: 'Residencial Sud' },
  { id: 332, id_city: 1, neighborhood: 'Residencial Velez Sarsfield' },
  { id: 333, id_city: 1, neighborhood: 'Rivadavia' },
  { id: 334, id_city: 1, neighborhood: 'Rivera Indarte' },
  { id: 335, id_city: 1, neighborhood: 'Rocio Del Sur' },
  { id: 336, id_city: 1, neighborhood: 'Rogelio Martinez' },
  { id: 337, id_city: 1, neighborhood: 'Rosedal' },
  { id: 338, id_city: 1, neighborhood: 'Sacchi' },
  { id: 339, id_city: 1, neighborhood: 'San Antonio' },
  { id: 340, id_city: 1, neighborhood: 'San Cayetano' },
  { id: 341, id_city: 1, neighborhood: 'San Daniel' },
  { id: 342, id_city: 1, neighborhood: 'San Felipe' },
  { id: 343, id_city: 1, neighborhood: 'San Fernando' },
  { id: 344, id_city: 1, neighborhood: 'San Francisco' },
  { id: 345, id_city: 1, neighborhood: 'San Ignacio' },
  { id: 346, id_city: 1, neighborhood: 'San Javier' },
  { id: 347, id_city: 1, neighborhood: 'San Jose' },
  { id: 348, id_city: 1, neighborhood: 'San Lorenzo Norte' },
  { id: 349, id_city: 1, neighborhood: 'San Lorenzo (s)' },
  { id: 350, id_city: 1, neighborhood: 'San Luis De Francia' },
  { id: 351, id_city: 1, neighborhood: 'San Marcelo' },
  { id: 352, id_city: 1, neighborhood: 'San Martin' },
  { id: 353, id_city: 1, neighborhood: 'San Martin Anexo' },
  { id: 354, id_city: 1, neighborhood: 'San Martin Norte' },
  { id: 355, id_city: 1, neighborhood: 'San Nicolas' },
  { id: 356, id_city: 1, neighborhood: 'San Pablo' },
  { id: 357, id_city: 1, neighborhood: 'San Pedro Nolasco' },
  { id: 358, id_city: 1, neighborhood: 'San Rafael' },
  { id: 359, id_city: 1, neighborhood: 'San Ramon' },
  { id: 360, id_city: 1, neighborhood: 'San Salvador' },
  { id: 361, id_city: 1, neighborhood: 'Santa Ana Residencial' },
  { id: 362, id_city: 1, neighborhood: 'Santa Cecilia' },
  { id: 363, id_city: 1, neighborhood: 'Santa Clara De Asis' },
  { id: 364, id_city: 1, neighborhood: 'Santa Isabel 1a Seccion' },
  { id: 365, id_city: 1, neighborhood: 'Santa Isabel 2a Seccion' },
  { id: 366, id_city: 1, neighborhood: 'Santa Isabel 3a Seccion' },
  { id: 367, id_city: 1, neighborhood: 'Santa Rita' },
  { id: 368, id_city: 1, neighborhood: 'Santa Rosa Residencial' },
  { id: 369, id_city: 1, neighborhood: 'San Vicente' },
  { id: 370, id_city: 1, neighborhood: 'Sargento Cabral' },
  { id: 371, id_city: 1, neighborhood: 'Sarmiento' },
  { id: 372, id_city: 1, neighborhood: 'SD' },
  { id: 373, id_city: 1, neighborhood: 'S.E.P.' },
  { id: 374, id_city: 1, neighborhood: 'Siete Soles' },
  { id: 375, id_city: 1, neighborhood: 'Sin Nombre' },
  { id: 376, id_city: 1, neighborhood: 'Smata' },
  { id: 377, id_city: 1, neighborhood: 'Solares De Santa Maria' },
  { id: 378, id_city: 1, neighborhood: 'Suarez' },
  { id: 379, id_city: 1, neighborhood: 'Tablada Park' },
  { id: 380, id_city: 1, neighborhood: 'Talleres (e)' },
  { id: 381, id_city: 1, neighborhood: 'Talleres (o)' },
  { id: 382, id_city: 1, neighborhood: 'Talleres Sud' },
  { id: 383, id_city: 1, neighborhood: 'Tejas De La Candelaria' },
  { id: 384, id_city: 1, neighborhood: 'Tejas Del Sur' },
  { id: 385, id_city: 1, neighborhood: 'Teodoro Fels' },
  { id: 386, id_city: 1, neighborhood: 'Tranviarios' },
  { id: 387, id_city: 1, neighborhood: 'Tte. Benjamin Matienzo' },
  { id: 388, id_city: 1, neighborhood: 'Universitario De Horizonte' },
  { id: 389, id_city: 1, neighborhood: 'U.o.c.r.a.' },
  { id: 390, id_city: 1, neighborhood: 'Urca' },
  { id: 391, id_city: 1, neighborhood: 'Uritorco' },
  { id: 392, id_city: 1, neighborhood: 'Urquiza' },
  { id: 393, id_city: 1, neighborhood: 'Valle Cercano' },
  { id: 394, id_city: 1, neighborhood: 'Valle Del Cerro' },
  { id: 395, id_city: 1, neighborhood: 'Valle Escondido' },
  { id: 396, id_city: 1, neighborhood: 'V.i.c.o.r.' },
  { id: 397, id_city: 1, neighborhood: 'Villa 9 De Julio' },
  { id: 398, id_city: 1, neighborhood: 'Villa Adela' },
  { id: 399, id_city: 1, neighborhood: 'Villa Alberdi' },
  { id: 400, id_city: 1, neighborhood: 'Villa Alberto' },
  { id: 401, id_city: 1, neighborhood: 'Villa Alberto Anexo' },
  { id: 402, id_city: 1, neighborhood: 'Villa Alicia Risler' },
  { id: 403, id_city: 1, neighborhood: 'Villa Allende Parque' },
  { id: 404, id_city: 1, neighborhood: 'Villa Argentina' },
  { id: 405, id_city: 1, neighborhood: 'Villa Aspasia' },
  { id: 406, id_city: 1, neighborhood: 'Villa Avalos' },
  { id: 407, id_city: 1, neighborhood: 'Villa Azalaiz' },
  { id: 408, id_city: 1, neighborhood: 'Villa Azalaiz Oeste' },
  { id: 409, id_city: 1, neighborhood: 'Villa Belgrano' },
  { id: 410, id_city: 1, neighborhood: 'Villa Bustos' },
  { id: 411, id_city: 1, neighborhood: 'Villa Cabrera' },
  { id: 412, id_city: 1, neighborhood: 'Villa Centenario' },
  { id: 413, id_city: 1, neighborhood: 'Villa Claret' },
  { id: 414, id_city: 1, neighborhood: 'Villa Claudina' },
  { id: 415, id_city: 1, neighborhood: 'Villa Corina' },
  { id: 416, id_city: 1, neighborhood: 'Villa Cornu' },
  { id: 417, id_city: 1, neighborhood: 'Villa Coronel Olmedo' },
  { id: 418, id_city: 1, neighborhood: 'Villa Derna' },
  { id: 419, id_city: 1, neighborhood: 'Villa El Libertador' },
  { id: 420, id_city: 1, neighborhood: 'Villa Esquiu' },
  { id: 421, id_city: 1, neighborhood: 'Villa Eucaristica' },
  { id: 422, id_city: 1, neighborhood: 'Villa General Urquiza' },
  { id: 423, id_city: 1, neighborhood: 'Villa Gran Parque' },
  { id: 424, id_city: 1, neighborhood: 'Villa Mafekin' },
  { id: 425, id_city: 1, neighborhood: 'Villa Marta' },
  { id: 426, id_city: 1, neighborhood: 'Villa Martinez' },
  { id: 427, id_city: 1, neighborhood: 'Villa Paez' },
  { id: 428, id_city: 1, neighborhood: 'Villa Quisquizacate' },
  { id: 429, id_city: 1, neighborhood: 'Villa Retiro' },
  { id: 430, id_city: 1, neighborhood: 'Villa Retiro De Horizonte' },
  { id: 431, id_city: 1, neighborhood: 'Villa Revol' },
  { id: 432, id_city: 1, neighborhood: 'Villa Revol Anexo' },
  { id: 433, id_city: 1, neighborhood: 'Villa Rivadavia Anexo "A"' },
  { id: 434, id_city: 1, neighborhood: 'Villa Rivera Indarte' },
  { id: 435, id_city: 1, neighborhood: 'Villa Saldan' },
  { id: 436, id_city: 1, neighborhood: 'Villa San Carlos' },
  { id: 437, id_city: 1, neighborhood: 'Villa San Isidro' },
  { id: 438, id_city: 1, neighborhood: 'Villa Serrana' },
  { id: 439, id_city: 1, neighborhood: 'Villa Siburu' },
  { id: 440, id_city: 1, neighborhood: 'Villa Silvano Funes' },
  { id: 441, id_city: 1, neighborhood: 'Villa Solferino' },
  { id: 442, id_city: 1, neighborhood: 'Villa Union' },
  { id: 443, id_city: 1, neighborhood: 'Villa Warcalde' },
  { id: 444, id_city: 1, neighborhood: 'Villa Zeppelin' },
  { id: 445, id_city: 1, neighborhood: 'Vivero Norte' },
  { id: 446, id_city: 1, neighborhood: 'Yapeyu' },
  { id: 447, id_city: 1, neighborhood: 'Yofre H' },
  { id: 448, id_city: 1, neighborhood: 'Yofre I' },
  { id: 449, id_city: 1, neighborhood: 'Yofre Norte' },
  { id: 450, id_city: 1, neighborhood: 'Yofre Sud' },
  { id: 451, id_city: 1, neighborhood: 'Zepa' }
]
